import { BaseSchema } from "../common/dto/base.dto";

export interface IReport extends BaseSchema {
  id?: number; // Optional because the 'id' will be automatically generated by PostgreSQL
  userID: number; // UserID from the User table
  type: 'monthly' | 'yearly'; // Type of report (monthly or yearly)
  generatedAt: Date;
  }
  